spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_system
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: admin